parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Resolver\Book\BookQueryResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\Resolver\Book\BookMutationResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\Resolver\Author\AuthorQueryResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\Resolver\Author\AuthorMutationResolverMap:
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }
